/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BodyLeft: typeof import('./components/bodyLeft.vue')['default']
    BodyMid: typeof import('./components/bodyMid.vue')['default']
    BodyRight: typeof import('./components/bodyRight.vue')['default']
    BodyRight1: typeof import('./components/bodyRight1.vue')['default']
    BodyRight2: typeof import('./components/bodyRight2.vue')['default']
    BottomTable: typeof import('./components/bottomTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
